# Generated by Django 6.1.1 on 2026-09-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('numero_de_billet', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('priorite', models.IntegerField(choices=[(0, 'Human'), (1, 'Saiyan'), (2, 'Super Saiyan')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('appele', models.BooleanField(default=False)),
                ('deja_appele', models.BooleanField(default=False)),
                ('numero_de_billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.billet')),
            ],
        ),
    ]
