# Generated by Django 6.1.1 on 2026-09-30 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pause_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteurEnAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('heure_sortie_prevue', models.DateTimeField()),
                ('billet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.enfile')),
            ],
        ),
    ]
