# Generated by Django 6.1.1 on 2026-09-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pushsubscription'),
        ('home', '0004_visiteurenattraction'),
    ]

    operations = [
    ]
