# Generated by Django 6.1.1 on 2026-09-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_0004_pushsubscription_0004_visiteurenattraction'),
        ('home', '0005_numero_billet_uuid'),
    ]

    operations = [
    ]
