# Generated by Django 6.1.1 on 2026-09-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_numero_billet_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteurenattraction',
            name='billet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.billet'),
        ),
    ]
