# Generated by Django 6.1.1 on 2026-09-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20260930_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfile',
            name='notification_10min_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enfile',
            name='notification_5min_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enfile',
            name='notification_appel_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enfile',
            name='notification_prochain_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
