# Generated by Django 6.1.1 on 2026-09-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_visiteurenattraction_billet'),
        ('home', '0007_enfile_notification_10min_envoyee_and_more'),
    ]

    operations = [
    ]
