# Generated by Django 6.1.1 on 2026-09-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20260930_1533'),
        ('home', '0008_merge_20260930_1552'),
        ('home', '0008_merge_20260930_1610'),
    ]

    operations = [
    ]
